### ISSUE TITLE
iPhone click not working

### ISSUE THREAD

**Issue by SufyanRamzan** [justcoded/jquery-stars#3]
by using this library none of the click events are working.

**Comment by aprokopenko** [comment]
We uploaded a new fix. please check how it works now: https://github.com/justcoded/jquery-stars/pull/4

**Comment by SufyanRamzan** [comment]
Hi @aprokopenko.
Thanks for the reply but still issue is coming.
on iPhone, form input field clicks not working and on android its trigger the double click when we click on any link or other clickable element also on android animation on touch/swipe not working like iPhone.

**Comment by aprokopenko** [comment]
Hi, thanks for more details.

Would be great if you can also provide an URL where we can see the error.

**Comment by SufyanRamzan** [comment]
Hi,

I really appreciate your prompt response, here you can see the live URL of the website: 
http://www.thumbsol.com/jquery-stars-test/


Also, I have one more thing to let you know, if we use latest jquery version (jquery-3.3.1.min.js) your library doesn't work properly that's why I am using the old version of jquery (jquery-2.2.4.min.js)

**Comment by aprokopenko** [comment]
We uploaded more fixes. Should work fine now on touch devices.
We will check compatibility with new jQuery, however this was a very very old plugin, which we created about 8 years ago. I'm impressed someone use it :)

**Comment by SufyanRamzan** [comment]
Hi thanks for the update it's working beautifully on mobile devices but with desktops with touch it wasn't working.
So I tweaked the code little bit like below:


```
if ('ontouchmove' in window) {
	this.addEventListener('touchmove', function (e) {
		hoverEvent(e);
	});

	if(!( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) )) {
		this.addEventListener('mousemove', function (e) {
			hoverEvent(e);
		});

	}
} else {
	this.addEventListener('mousemove', function (e) {
		hoverEvent(e);
	});
}
```
